export default {
    FETCH_TODOS: 'FETCH_TODOS',
    FETCH_TODO: 'FETCH_TODO',
    SET_TODO: 'SET_TODO',
    CREATE_TODO: 'CREATE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO'
}